### PR TITLE
Added support of ChoiceParameterDefinition

### PR DESCRIPTION
**Pull request by jhaeyaert**
This pull request allow to add support of ChoiceParameterDefinition in addition of StringParameterDefinition.

### CODE REVIEW

**Comment by elvanja** [comment]
Hi, so basically this is just an addition that makes hook accept ```ChoiceParameterDefinition``` parameters as well. But, where is the code that sets the value of such parameter? Did you test this on a live instance?

**Comment by jhaeyaert** [comment]
Hi,

Yes I tested it on a live instance and it works well. Basically, I have a Jenkins job that takes a choice parameter named BRANCH. I can manually launch the job selecting the branch that I want to build or I can just let the GitLab hook provide the ${BRANCH} parameter and launch the job for me when I push my code on the repository.

I also tested it with the FULL_BRANCH_REFERENCE parameter name and it works too. I haven't tested it with other parameters but I suppose It works the same.

So I suppose there is nothing else to do ?

Thanks

**Comment by elvanja** [comment]
How does it behave if the choice is not found in available options?
E.g. you added "master" and "develop" but "featureX" is filled from Gitlab payload?

**Comment by jhaeyaert** [comment]
It's not a problem cause Jenkins allow to specify a value even if it is not part of the list.
I've tested this case (create a new branch and push it) and Jenkins is able to build the branch even if I haven't added the branch into the list.

**Comment by elvanja** [comment]
I've merged it and fixed failing test (also altered the code a bit). You can find this in latest release v1.2.1. If you're in a hurry, you can download manually from http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/ruby-plugins/gitlab-hook/1.2.1

**Pull request merged**
